[tool.pytest.ini_options]
#Параметры конфигурации запуска. Применяются по-умолчанию, не нужно вводить при каждом запуске
addopts = "-l -v --durations=10 --color=yes"
#Описание марок используемые в проекте
markers = [
    "product: Тесты класса продукты",
    "buy: Тесты метода покупки",
    "check: Тесты метода проверки количества продуктов"
]