[tool.pytest.ini_options]
#Параметры конфигурации запуска. Применяются по-умолчанию, не нужно вводить при каждом запуске
addopts = [
    "-v",
    "-l",
    "--durations=10",
    "--color=yes",
    #С этой опцией он показывает полные названия всех тестов. Без этой опции pytest может показывать только точки
    "--verbose"
]
#Описание марок используемые в проекте
markers = [
    "product: Тесты класса продукты",
    "buy: Тесты метода покупки",
    "check: Тесты метода проверки количества продуктов"
]

#Отключить экранирование = Перестать прятать русские буквы за кодами
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true
#С этой опцией он показывает полные названия всех тестов. Без этой опции pytest может показывать только точки
#verbose = true